routes/web.php
<?php

use App\User;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// ERROR: Cannot use Illuminate\Support\Facades\Route as Route because the name is already in use
//use Illuminate\Support\Facades\Route;
//use Illuminate\Support\Facades\Auth;

Route::get('/', function () {
    if (Auth::check())
        return redirect()->route('home');
    else
        return redirect()->route('login');
});

// Register login, register, password-reset, and other lovely core stuff.
Auth::routes();

Route::get('register/thanks', 'Auth\RegisterController@thanks')->name('register.thanks');
Route::get('register/to/{city_slug}/{section_id}', 'Auth\RegisterController@sectionPreload')->name('register.tosection');

// **** developer stuff ****************************

Route::prefix('dev')->group(function () {
    // We support useful but very-dangerous auto-login workflows,
    // but first, you MUST have:
    //  - environment: local
    //  - env UNSAFE_QUICK_LOGIN_BACKDOOR: 1
    if (!app()->environment('local') || !env('DEV_QUICK_LOGIN_BACKDOOR')) {
        return;
    }

    Route::prefix('login')->group(function () {

        Route::get('admin', function () {
            $user = User::active()->ofRole('admin')->first();
            auth()->login($user);

            return redirect()->route('home');
        })->name('dev.login.admin');

        Route::get('member', function () {
            $user = User::active()->ofRole('member')->first();
            auth()->login($user);

            return redirect()->route('home');
        })->name('dev.login.member');

        Route::get('referent', function () {
            $user = User::active()->ofRole('referent')->first();
            auth()->login($user);

            return redirect()->route('home');
        })->name('dev.login.referent');

        Route::get('pending', function () {
            $user = User::pendingWithPaidFee()->first();
            auth()->login($user);

            return redirect()->route('home');
        })->name('dev.login.pending');

        Route::get('suspended', function () {
            $user = User::ofStatus('suspended')->first();
            auth()->login($user);

            return redirect()->route('home');
        })->name('dev.login.suspended');

        Route::get('expelled', function () {
            $user = User::ofStatus('expelled')->first();
            auth()->login($user);

            return redirect()->route('home');
        })->name('dev.login.expelled');

        Route::get('dropped', function () {
            $user = User::ofStatus('dropped')->first();
            auth()->login($user);

            return redirect()->route('home');
        })->name('dev.login.dropped');

        Route::get('association', function () {
            $user = User::actLikeMember()
              ->ofType('association')->first();
            auth()->login(User::find($user->id));

            return redirect()->route('home');
        })->name('dev.login.association');

        Route::get('limited', function () {
            $user = User::ofType('limited')->first();
            auth()->login($user);
            return redirect()->route('home');
        })->name('dev.login.limited');
    });
});

Route::middleware(['auth'])->group(function () {
    Route::get('home', 'HomeController@index')->name('home');

    Route::post('user/approve', 'UserController@approve')->name('user.approve');
    Route::get('user/bypass/{id}', 'UserController@bypass')->name('user.bypass');

    Route::get('movement/review', 'MovementController@review')->name('movement.review');
    Route::post('movement/attach/{id}', 'MovementController@attach')->name('movement.attach');
    Route::post('movement/refresh/{id}', 'MovementController@refresh')->name('movement.refresh');
    Route::post('movement/refund/{id}', 'MovementController@refund')->name('movement.refund');
    Route::get('movement/{id}/download/{file}', 'MovementController@download')->name('movement.download');

    Route::get('movement-detailed/export/all/csv', 'MovementDetailedController@exportAllCsv')->name('movement-detailed.export.all.csv');

    Route::get('section/{id}/balance', 'SectionController@balance')->name('section.balance');
    Route::post('section/{id}/exportmembers', 'SectionController@exportmembers')->name('section.exportmembers');

    Route::get('refund/{id}/download/quote/{file}', 'RefundController@downloadQuote')->name('refund.quote.download');
    Route::get('refund/{id}/download/receipt/{file}', 'RefundController@downloadReceipt')->name('refund.receipt.download');

    Route::get('sponsor/logo/{id}', 'SponsorController@logo')->name('sponsor.logo');

    Route::get('doc/download', 'DocumentationController@download')->name('doc.download');
    Route::get('doc/link', 'DocumentationController@link')->name('doc.link');
    Route::get('doc/preview', 'DocumentationController@preview')->name('doc.preview');

    Route::post('assembly/partecipate/{assembly_id}/{do}', 'AssemblyController@partecipate')->name('assembly.partecipate');
    Route::post('assembly/delegate/{assembly_id}/{delegate_id}', 'AssemblyController@delegate')->name('assembly.delegate');

   // Route::get('bank/list/', 'BankController@list')->name('bank.list_all');
   // Route::get('bank/list/{id}', 'BankController@list')->name('bank.list');

    Route::resource('user', 'UserController');
    Route::resource('volunteer', 'VolunteerController');
    Route::resource('doc', 'DocumentationController');
    Route::resource('config', 'ConfigController');
    Route::resource('bank', 'BankController');
    Route::resource('movement', 'MovementController');
    Route::resource('movement-detailed', 'MovementDetailedController');
    Route::resource('rule', 'RuleController');
    Route::resource('section', 'SectionController');
    Route::resource('receipt', 'ReceiptController');
    Route::resource('refund', 'RefundController');
    Route::resource('assembly', 'AssemblyController');
    Route::resource('votation', 'VotationController');
    Route::resource('vote', 'VoteController');
    Route::resource('sponsor', 'SponsorController');
    Route::resource('gadget-request', 'GadgetRequestController');
});

// Rotte per gli utenti ospiti
Route::get('gadget-request-track/{token}', 'GadgetRequestController@showByToken')->name('gadget-request.show-by-token');
Route::get('gadget-request-thank-you', 'GadgetRequestController@thankYou')->name('gadget-request.thank-you');
Route::get('gadget-request/create', 'GadgetRequestController@create')->name('gadget-request.create');
Route::post('gadget-request/store', 'GadgetRequestController@store')->name('gadget-request.store');

app/Movement.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Collection;

use DB;
use Exception;

use App\AccountRow;
use App\Config;

/**
 * A Movement is a money transfer from (or to) your bank account(s).
 * A Movement may create AccountRow(s).
 * Each Movement may generate a single Receipt.
 */
class Movement extends Model
{

    use ILSModel;

    /**
     * Get the attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'date' => 'datetime',
    ];

    public function getEntityNameSingular()
    {
        return "Movimento";
    }

    public function bank()
    {
        return $this->belongsTo('App\Bank');
    }

    public function account_rows()
    {
        return $this->hasMany('App\AccountRow')->with('user');
    }

    public function receipt()
    {
        return $this->hasOne('App\Receipt');
    }

    public function refund()
    {
        return $this->hasMany('App\Refund');
    }

    /**
     * Scope a query to only include movements related to an Unicredit bank.
     */
    public function scopeUnicredit(Builder $query): void
    {
        $query->whereHas('bank', function ($bank_query) {
            $bank_query->unicredit();
        });
    }

    public function getAmountFormattedAttribute() {
        return format_amount( $this->amount );
    }

    public function getAmountOriginalFormattedAttribute() {
        return format_amount( $this->amount_original );
    }

    public function getAttachmentsPathAttribute()
    {
        return storage_path('accounting/' . $this->id);
    }

    public function getAttachmentsAttribute()
    {
        $ret = new Collection();

        $path = $this->attachments_path;
        if (file_exists($path)) {
            $files = scandir($path);

            foreach($files as $f) {
                if ($f[0] === '.')
                    continue;

                $ret->push($f);
            }
        }

        return $ret;
    }

    /**
     * Get the year of this Movement's date.
     *
     * @return int Year of the date
     */
    public function getDateYearAttribute()
    {
        if( !$this->date ) {
            throw new \Exception("No date, no party");
        }
        return (int) substr($this->date, 0, 4);
    }

    /**
     * Get the already-imported Movement with big margin of confidence.
     * The confidence is low on Unicredit, since there, we historically had no identifier.
     * You may want to then also run Movement#isExactlySameMovement($other) to be 100% sure.
     * @return Movement|null
     */
    public function alreadyTrackedMovement()
    {
        $query = Movement::query();

        // Skip myself if I'm already persisted.
        if (!empty($this->id))
        {
            $query = $query->where('id', '<>', $this->id);
        }

        // Base condition. Look for the copy of myself under the same bank.
        $query = $query->where('bank_id', $this->bank_id);

        // If the bank+identifier is available, use just these robust info.
        if (!empty($this->identifier))
        {
              $query = $query->where('identifier', $this->identifier);
        }
        else
        {
            // No identifier. Do desperate things.
            // Pitfall: Unicredit randomly changes "notes"...
            $query = $query->where('date', $this->date)
                           ->where('amount', $this->amount)
                           ->where('notes', $this->notes);
        }

        return $query->first();
    }

    /**
     * Check if this (non-persisted) Movement was already imported.
     * @return bool
     */
    public function alreadyTracked()
    {
        return !is_null( $this->alreadyTrackedMovement() );
    }

    /**
     * Check whenever two Movements are really the same thing.
     * This is supposed to check for everything, but the id.
     * @param Movement
     * @return bool
     */
    public function isExactlySameMovement($other)
    {
        // Limit days of difference between the two movements.
        // It happened to have a PayPal movement imported as 2024-01-09 but then moved
        // from PayPal to 2023-12-29, so, in a different year, with same identifier. lol
        $max_days_diff = 30;

        // The identifier is supposed to be unique for the whole history of the bank
        // for myself as customer.
        // This seems untrue for PayPal, that has API errors if you try to download
        // a specific Transaction ID without a date. So I guess the identifier
        // is probably unique by year :) So this is a reasonable strong check.
        return $this->bank_id    ==  $other->bank_id
            && !is_null($this->identifier)
            && $this->identifier === $other->identifier
            && $this->date->diffInDays($other->date) < $max_days_diff;
    }

    public function attachFile($file)
    {
        $file->move($this->attachments_path, $file->getClientOriginalName());
    }

    /**
     * Append some proposed AccountRow(s) covering membership fees.
     * This method tries to update already-existing AccountRow(s).
     * To recognize which of them were created, loop your "account_rows"
     * and look for ones without an "id" or with "edited".
     * @return boolean
     */
    public function proposeMembershipFeesForUser($user)
    {
        if (!is_object($user)) {
            $user_id = $user;
            $user = User::find($user_id);
            if (is_null($user)) {
                Log::error('Errore nel riconoscimento utente di cui generare le quote di iscrizione: ' . $user_id);
                return false;
            }
        }

        $fees_account = Config::feesAccount();
        $donations_account = Account::where('donations', true)->first();
        $year = $user->firstMissingFeeYear();

        // First, try expanding an already-existing stub AccountRow.
        $already_existing_ar = $this->findStubAccountRow();
        $ar = $already_existing_ar;
        if ($ar) {
            $amount = $ar->amount;
        } else {
            $amount = $this->getAccountRowsAmountDiffError();
        }

        while($amount >= $user->feeAmount) {
            // Add a new AccountRow or expand the initial one.
            if (!$ar) {
                $ar = new AccountRow;
                $ar->movement_id = $this->id;
            }
            $ar->account_id = $fees_account->id;
            $ar->amount = $user->feeAmount;
            $ar->user_id = $user->id;
            $ar->notes = AccountRow::createFeeNote($user, $year);
            if ($ar === $already_existing_ar) {
                $ar->edited = true;
            } else {
                $this->account_rows->push($ar);
            }

            $amount = bcsub($amount, $user->feeAmount, 2);
            $year++;

            // Force the creation of a new AccountRow on the next run.
            $ar = null;
        }

        if ($amount > 0) {
            if (!$ar) {
                $ar = new AccountRow;
                $ar->movement_id = $this->id;
            }
            $ar->account_id = $donations_account->id;
            $ar->amount = $amount;
            $ar->notes = sprintf('Donazione da parte di %s', $user->printable_name);
            $ar->user_id = $user->id;
            if ($ar === $already_existing_ar) {
                $ar->edited = true;
            } else {
                $this->account_rows->push($ar);
            }
        }

        return true;
    }

    /**
     * Find the most recent Account Row from the whole history, using a generic note
     *
     * @param string $guess_by_note
     * @return AccountRow
     */
    public function proposeAccountRowFromHistory($guess_by_note)
    {
        // Get the already-saved AccountRow's Account IDs.
        // This is useful since probably we wont to import what remains.
        $current_account_ids = $this->account_rows->pluck('account_id');

        $prev_movement_query = Movement::query()
          ->where('notes', 'like', $guess_by_note)
          ->whereHas('account_rows', function($query) use ($current_account_ids) {
              if ($current_account_ids) {
                  $query->whereNotIn('account_id', $current_account_ids);
              }
          })
          ->orderBy('id', 'desc');

        // Do not suggest myself.
        if ($this->id) {
            $prev_movement_query->whereNot('id', $this->id);
        }

        $prev_movement = $prev_movement_query->first();
        if ($prev_movement) {
            $prev_account_row = $prev_movement->account_rows()->first();
            if ($prev_account_row) {
                $remaining_amount = $this->getAccountRowsAmountDiffError();
                $remaining_plus_fee = bcadd($remaining_amount, $prev_account_row->amount, 2);
                if ($remaining_plus_fee > 0) {
                    $ar = new AccountRow;
                    $ar->movement_id = $this->id;
                    $ar->account_id = $prev_account_row->account_id;
                    $ar->user_id = $prev_account_row->user_id;
                    $ar->section_id = $prev_account_row->section_id;
                    $ar->notes = $prev_account_row->notes;
                    $ar->amount = $prev_account_row->amount;
                }
                return $ar;
            }
        }

        return null;
    }

    /**
     * Try to give a meaning to this Movement, from its note.
     * You can setup some regular expressions in each Bank configuration,
     * to match your Movement and propose an AccountRow.
     *
     * This method MAY modify some already-existing AccountRow(s) but
     * WITHOUT PERSISTING ANYTHING. Or, this method will just return some new
     * proposed AccountRow.
     *
     * To know what AccountRow was created or expanded, just look at what
     * AccountRow is flagged as "edited".
     *

resources/views/movement-detailed/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12 mt-3">

            @if ($limit > 0)
                <h5 id="bank-last-movements">Ultimi {{ $limit }} Movimenti Bancari</h5>
            @else
                <h5 id="bank-last-movements">Movimenti Bancari</h5>
            @endif

            <p>Ogni Movimento bancario è dettagliato da una o più Righe Contabili.</p>
                <form method="GET" action="" class="auto-filter-form">
                    <div class="row mt-3">
                        <div class="col-md-3">
                            <div class="form-group">
                                <label for="year">Anno:</label>
                                <select id="year" name="year" class="form-control">
                                    <option value="-" @selected($year === null)>Tutti</option>
                                    @foreach (array_reverse(range(date('Y')-10, date('Y'))) as $available_year)
                                        <option value="{{ $available_year }}" @selected($year == $available_year)>{{ $available_year }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>

                        <div class="col-md-3">
                            <div class="form-group">
                                <label for="bank_id">Banca:</label>
                                <select id="bank_id" name="bank_id" class="form-control">
                                    <option value="">Tutte le Banche</option>
                                    @foreach ($banks as $bank)
                                        <option value="{{ $bank->id }}" @selected($bank->id == $bank_id)>{{ $bank->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>

                        <div class="col-md-3">
                            <div class="form-group">
                                <label for="with_start_of_year">Includi bilancio di inizio anno:</label>
                                <input type="checkbox" id="with_start_of_year" name="with_start_of_year" class="form-control" @checked($with_start_of_year)>
                            </div>
                        </div>

                        <div class="col-md-3">
                            <label>Conti economici:</label>
                            <div style="max-height: 143px; overflow-y: scroll">
                                @include('account/multiselect', [
                                    'selected_account_ids' => $selected_account_ids,
                                ])
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-3">
                            @include('commons/orderby', [
                                'availables_order_dir' => $availables_order_dir,
                                'order_dir' => $order_dir,
                            ])
                        </div>
                        <div class="col-md-3">
                            @include('commons/limit', [
                                'limit' => $limit,
                            ])
                        </div>
                    </div>
                </form>
            <p><a href="{{ route('movement-detailed.export.all.csv', [
                'year' => $year,
                'bank_id' => $bank_id,
                'account' => $selected_account_ids,
                'order_dir' => $order_dir,
                'limit' => $limit,
            ]) }}">Esporta in CSV</a></p>
        </div>
    </div>
</div>

<div>
    <div class="row">
        <div class="col-md-10 offset-md-1">

            <table class="table">
                <thead>
                    <tr>
                        <th><!-- Actions --></th>
                        <th colspan="4">Movimenti Bancari</th>
                        <th colspan="7" class="border-left">Movimenti in Dettaglio (Righe Contabili)</th>
                    </tr>
                    <tr>
                        <th>ID<br />Movimento</th>
                        <th>Banca<br />Movimento</th>
                        <th>Data<br />Movimento</th>
                        <th>Causale<br />Originale</th>
                        <th>Importo<br />Bancario</th>
                        <th class="border-left">Dettaglio<br />Importo</th>
                        <th>Account<br />Contabile</th>
                        <th>Causale<br />Riga Contabile</th>
                        <th>Utente<br />&nbsp;</th>
                        <th>Sezione<br />Locale</th>
                        <th>Anno<br />Quota</th>
                    </tr>
                </thead>
                <tbody>
                        @foreach ($movements_dto as $movement_dto)

                            @php
                            $error = null;
                            try {
                                $movement_dto['movement']->validate();
                            } catch(Exception $e) {
                                $error = $e;
                            }
                            @endphp

                            <tr class="{{ $error ? 'bg-warning' : '' }}">
                                @if ($movement_dto['account_row_first'])
                                    <td><a href="{{ route('movement.edit', $movement_dto['movement']->id) }}" title="Modifica Movimento {{ $movement_dto['movement']->id }} del {{ $movement_dto['movement']->date }}"><span class="oi oi-pencil"></span> {{ $movement_dto['movement']->id }}</a></td>
                                    <td><a href="{{ route('bank.edit', $movement_dto['movement']->bank_id) }}" title="Modifica Banca: {{ $movement_dto['movement']->bank->name }}">{{ $movement_dto['movement']->bank->name }}</a></td>
                                    <td>{{ $movement_dto['movement']->date }}</td>
                                    <td>{{ $movement_dto['movement']->notes }}</td>
                                    <td>{{ $movement_dto['movement']->amount_formatted }}</td>
                                @else
                                    <td><!-- Edit Movement already printed --></td>
                                    <td><abbr title="{{ $movement_dto['movement']->bank->name }}">&hellip;</abbr></td>
                                    <td><abbr title="{{ $movement_dto['movement']->date }}">&hellip;</abbr></td>
                                    <td><abbr title="{{ $movement_dto['movement']->notes }}">&hellip;</abbr></td>
                                    <td class="text-right"><abbr title="{{ $movement_dto['movement']->amount_formatted }}">&hellip;</abbr></td>
                                @endif

                                <td class="border-left text-right {{ $movement_dto['movement']->isAmountMatchingAccountRows() ?: 'bg-danger' }}">
                                    {{ $movement_dto['account_row'] ? $movement_dto['account_row']->amount_formatted : '' }}
                                </td>

                                <td>{{ isset($movement_dto['account_row']->account) ? $movement_dto['account_row']->account->name : '' }}</td>
                                <td>{{ $movement_dto['account_row']           ? $movement_dto['account_row']->notes         : '' }}</td>

                                <td>
                                @if ( $movement_dto['account_row'] && $movement_dto['account_row']->user )
                                <a href="{{ route('user.edit', $movement_dto['account_row']->user->id) }}">{{ $movement_dto['account_row']->user->printableName }}</a>
                                @endif
                                </td>

                                <td>
                                @if ( $movement_dto['account_row'] && $movement_dto['account_row']->section )
                                <a href="{{ route('section.edit', $movement_dto['account_row']->section->id) }}">{{ $movement_dto['account_row']->section->city }}</a>
                                @endif
                                </td>

                                <td>{{ $movement_dto['fee'] ? $movement_dto['fee']->year : '' }}</td>
                            </tr>

                            @if ($error)
                                <tr class="bg-warning">
                                    <td>&nbsp;</td>
                                    <td colspan="10"><b>{{ $e->getMessage() }}</b></td>
                                </tr>
                            @endif

                        @endforeach
                </tbody>
                <tfoot>
                    <tr>
                        <th>TOTALI</th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th title="Somma dei Movimenti bancari">{{ $movements_amount_sum }}</th>
                        <th title="Somma dei dettagli delle righe contabili">{{ $account_rows_amount_sum }}</th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                    </tr>
                </tfoot>
            </table>
            <div class="pagination-wrapper">
                {{ $movements->appends(request()->query())->links() }}
            </div>
        </div>
    </div>
</div>
@endsection