routes/web.php
<?php

use App\User;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// ERROR: Cannot use Illuminate\Support\Facades\Route as Route because the name is already in use
//use Illuminate\Support\Facades\Route;
//use Illuminate\Support\Facades\Auth;

Route::get('/', function () {
    if (Auth::check())
        return redirect()->route('home');
    else
        return redirect()->route('login');
});

// Register login, register, password-reset, and other lovely core stuff.
Auth::routes();

Route::get('register/thanks', 'Auth\RegisterController@thanks')->name('register.thanks');
Route::get('register/to/{city_slug}/{section_id}', 'Auth\RegisterController@sectionPreload')->name('register.tosection');

// **** developer stuff ****************************

Route::prefix('dev')->group(function () {
    // We support useful but very-dangerous auto-login workflows,
    // but first, you MUST have:
    //  - environment: local
    //  - env UNSAFE_QUICK_LOGIN_BACKDOOR: 1
    if (!app()->environment('local') || !env('DEV_QUICK_LOGIN_BACKDOOR')) {
        return;
    }

    Route::prefix('login')->group(function () {

        Route::get('admin', function () {
            $user = User::active()->ofRole('admin')->first();
            auth()->login($user);

            return redirect()->route('home');
        })->name('dev.login.admin');

        Route::get('member', function () {
            $user = User::active()->ofRole('member')->first();
            auth()->login($user);

            return redirect()->route('home');
        })->name('dev.login.member');

        Route::get('referent', function () {
            $user = User::active()->ofRole('referent')->first();
            auth()->login($user);

            return redirect()->route('home');
        })->name('dev.login.referent');

        Route::get('pending', function () {
            $user = User::pendingWithPaidFee()->first();
            auth()->login($user);

            return redirect()->route('home');
        })->name('dev.login.pending');

        Route::get('suspended', function () {
            $user = User::ofStatus('suspended')->first();
            auth()->login($user);

            return redirect()->route('home');
        })->name('dev.login.suspended');

        Route::get('expelled', function () {
            $user = User::ofStatus('expelled')->first();
            auth()->login($user);

            return redirect()->route('home');
        })->name('dev.login.expelled');

        Route::get('dropped', function () {
            $user = User::ofStatus('dropped')->first();
            auth()->login($user);

            return redirect()->route('home');
        })->name('dev.login.dropped');

        Route::get('association', function () {
            $user = User::actLikeMember()
              ->ofType('association')->first();
            auth()->login(User::find($user->id));

            return redirect()->route('home');
        })->name('dev.login.association');

        Route::get('limited', function () {
            $user = User::ofType('limited')->first();
            auth()->login($user);
            return redirect()->route('home');
        })->name('dev.login.limited');
    });
});

Route::middleware(['auth'])->group(function () {
    Route::get('home', 'HomeController@index')->name('home');

    Route::post('user/approve', 'UserController@approve')->name('user.approve');
    Route::get('user/bypass/{id}', 'UserController@bypass')->name('user.bypass');

    Route::get('movement/review', 'MovementController@review')->name('movement.review');
    Route::post('movement/attach/{id}', 'MovementController@attach')->name('movement.attach');
    Route::post('movement/refresh/{id}', 'MovementController@refresh')->name('movement.refresh');
    Route::post('movement/refund/{id}', 'MovementController@refund')->name('movement.refund');
    Route::get('movement/{id}/download/{file}', 'MovementController@download')->name('movement.download');

    Route::get('movement-detailed/export/all/csv', 'MovementDetailedController@exportAllCsv')->name('movement-detailed.export.all.csv');

    Route::get('section/{id}/balance', 'SectionController@balance')->name('section.balance');
    Route::post('section/{id}/exportmembers', 'SectionController@exportmembers')->name('section.exportmembers');

    Route::get('refund/{id}/download/quote/{file}', 'RefundController@downloadQuote')->name('refund.quote.download');
    Route::get('refund/{id}/download/receipt/{file}', 'RefundController@downloadReceipt')->name('refund.receipt.download');

    Route::get('sponsor/logo/{id}', 'SponsorController@logo')->name('sponsor.logo');

    Route::get('doc/download', 'DocumentationController@download')->name('doc.download');
    Route::get('doc/link', 'DocumentationController@link')->name('doc.link');
    Route::get('doc/preview', 'DocumentationController@preview')->name('doc.preview');

    Route::post('assembly/partecipate/{assembly_id}/{do}', 'AssemblyController@partecipate')->name('assembly.partecipate');
    Route::post('assembly/delegate/{assembly_id}/{delegate_id}', 'AssemblyController@delegate')->name('assembly.delegate');

   // Route::get('bank/list/', 'BankController@list')->name('bank.list_all');
   // Route::get('bank/list/{id}', 'BankController@list')->name('bank.list');

    Route::resource('user', 'UserController');
    Route::resource('volunteer', 'VolunteerController');
    Route::resource('doc', 'DocumentationController');
    Route::resource('config', 'ConfigController');
    Route::resource('bank', 'BankController');
    Route::resource('movement', 'MovementController');
    Route::resource('movement-detailed', 'MovementDetailedController');
    Route::resource('rule', 'RuleController');
    Route::resource('section', 'SectionController');
    Route::resource('receipt', 'ReceiptController');
    Route::resource('refund', 'RefundController');
    Route::resource('assembly', 'AssemblyController');
    Route::resource('votation', 'VotationController');
    Route::resource('vote', 'VoteController');
    Route::resource('sponsor', 'SponsorController');
    Route::resource('gadget-request', 'GadgetRequestController');
});

// Rotte per gli utenti ospiti
Route::get('gadget-request-track/{token}', 'GadgetRequestController@showByToken')->name('gadget-request.show-by-token');
Route::get('gadget-request-thank-you', 'GadgetRequestController@thankYou')->name('gadget-request.thank-you');
Route::get('gadget-request/create', 'GadgetRequestController@create')->name('gadget-request.create');
Route::post('gadget-request/store', 'GadgetRequestController@store')->name('gadget-request.store');

app/Movement.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Collection;

use DB;
use Exception;

use App\AccountRow;
use App\Config;

/**
 * A Movement is a money transfer from (or to) your bank account(s).
 * A Movement may create AccountRow(s).
 * Each Movement may generate a single Receipt.
 */
class Movement extends Model
{

    use ILSModel;

    /**
     * Get the attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'date' => 'datetime',
    ];

    public function getEntityNameSingular()
    {
        return "Movimento";
    }

    public function bank()
    {
        return $this->belongsTo('App\Bank');
    }

    public function account_rows()
    {
        return $this->hasMany('App\AccountRow')->with('user');
    }

    public function receipt()
    {
        return $this->hasOne('App\Receipt');
    }

    public function refund()
    {
        return $this->hasMany('App\Refund');
    }

    /**
     * Scope a query to only include movements related to an Unicredit bank.
     */
    public function scopeUnicredit(Builder $query): void
    {
        $query->whereHas('bank', function ($bank_query) {
            $bank_query->unicredit();
        });
    }

    public function getAmountFormattedAttribute() {
        return format_amount( $this->amount );
    }

    public function getAmountOriginalFormattedAttribute() {
        return format_amount( $this->amount_original );
    }

    public function getAttachmentsPathAttribute()
    {
        return storage_path('accounting/' . $this->id);
    }

    public function getAttachmentsAttribute()
    {
        $ret = new Collection();

        $path = $this->attachments_path;
        if (file_exists($path)) {
            $files = scandir($path);

            foreach($files as $f) {
                if ($f[0] === '.')
                    continue;

                $ret->push($f);
            }
        }

        return $ret;
    }

    /**
     * Get the year of this Movement's date.
     *
     * @return int Year of the date
     */
    public function getDateYearAttribute()
    {
        if( !$this->date ) {
            throw new \Exception("No date, no party");
        }
        return (int) substr($this->date, 0, 4);
    }

    /**
     * Get the already-imported Movement with big margin of confidence.
     * The confidence is low on Unicredit, since there, we historically had no identifier.
     * You may want to then also run Movement#isExactlySameMovement($other) to be 100% sure.
     * @return Movement|null
     */
    public function alreadyTrackedMovement()
    {
        $query = Movement::query();

        // Skip myself if I'm already persisted.
        if (!empty($this->id))
        {
            $query = $query->where('id', '<>', $this->id);
        }

        // Base condition. Look for the copy of myself under the same bank.
        $query = $query->where('bank_id', $this->bank_id);

        // If the bank+identifier is available, use just these robust info.
        if (!empty($this->identifier))
        {
              $query = $query->where('identifier', $this->identifier);
        }
        else
        {
            // No identifier. Do desperate things.
            // Pitfall: Unicredit randomly changes "notes"...
            $query = $query->where('date', $this->date)
                           ->where('amount', $this->amount)
                           ->where('notes', $this->notes);
        }

        return $query->first();
    }

    /**
     * Check if this (non-persisted) Movement was already imported.
     * @return bool
     */
    public function alreadyTracked()
    {
        return !is_null( $this->alreadyTrackedMovement() );
    }

    /**
     * Check whenever two Movements are really the same thing.
     * This is supposed to check for everything, but the id.
     * @param Movement
     * @return bool
     */
    public function isExactlySameMovement($other)
    {
        // Limit days of difference between the two movements.
        // It happened to have a PayPal movement imported as 2024-01-09 but then moved
        // from PayPal to 2023-12-29, so, in a different year, with same identifier. lol
        $max_days_diff = 30;

        // The identifier is supposed to be unique for the whole history of the bank
        // for myself as customer.
        // This seems untrue for PayPal, that has API errors if you try to download
        // a specific Transaction ID without a date. So I guess the identifier
        // is probably unique by year :) So this is a reasonable strong check.
        return $this->bank_id    ==  $other->bank_id
            && !is_null($this->identifier)
            && $this->identifier === $other->identifier
            && $this->date->diffInDays($other->date) < $max_days_diff;
    }

    public function attachFile($file)
    {
        $file->move($this->attachments_path, $file->getClientOriginalName());
    }

    /**
     * Append some proposed AccountRow(s) covering membership fees.
     * This method tries to update already-existing AccountRow(s).
     * To recognize which of them were created, loop your "account_rows"
     * and look for ones without an "id" or with "edited".
     * @return boolean
     */
    public function proposeMembershipFeesForUser($user)
    {
        if (!is_object($user)) {
            $user_id = $user;
            $user = User::find($user_id);
            if (is_null($user)) {
                Log::error('Errore nel riconoscimento utente di cui generare le quote di iscrizione: ' . $user_id);
                return false;
            }
        }

        $fees_account = Config::feesAccount();
        $donations_account = Account::where('donations', true)->first();
        $year = $user->firstMissingFeeYear();

        // First, try expanding an already-existing stub AccountRow.
        $already_existing_ar = $this->findStubAccountRow();
        $ar = $already_existing_ar;
        if ($ar) {
            $amount = $ar->amount;
        } else {
            $amount = $this->getAccountRowsAmountDiffError();
        }

        while($amount >= $user->feeAmount) {
            // Add a new AccountRow or expand the initial one.
            if (!$ar) {
                $ar = new AccountRow;
                $ar->movement_id = $this->id;
            }
            $ar->account_id = $fees_account->id;
            $ar->amount = $user->feeAmount;
            $ar->user_id = $user->id;
            $ar->notes = AccountRow::createFeeNote($user, $year);
            if ($ar === $already_existing_ar) {
                $ar->edited = true;
            } else {
                $this->account_rows->push($ar);
            }

            $amount = bcsub($amount, $user->feeAmount, 2);
            $year++;

            // Force the creation of a new AccountRow on the next run.
            $ar = null;
        }

        if ($amount > 0) {
            if (!$ar) {
                $ar = new AccountRow;
                $ar->movement_id = $this->id;
            }
            $ar->account_id = $donations_account->id;
            $ar->amount = $amount;
            $ar->notes = sprintf('Donazione da parte di %s', $user->printable_name);
            $ar->user_id = $user->id;
            if ($ar === $already_existing_ar) {
                $ar->edited = true;
            } else {
                $this->account_rows->push($ar);
            }
        }

        return true;
    }

    /**
     * Find the most recent Account Row from the whole history, using a generic note
     *
     * @param string $guess_by_note
     * @return AccountRow
     */
    public function proposeAccountRowFromHistory($guess_by_note)
    {
        // Get the already-saved AccountRow's Account IDs.
        // This is useful since probably we wont to import what remains.
        $current_account_ids = $this->account_rows->pluck('account_id');

        $prev_movement_query = Movement::query()
          ->where('notes', 'like', $guess_by_note)
          ->whereHas('account_rows', function($query) use ($current_account_ids) {
              if ($current_account_ids) {
                  $query->whereNotIn('account_id', $current_account_ids);
              }
          })
          ->orderBy('id', 'desc');

        // Do not suggest myself.
        if ($this->id) {
            $prev_movement_query->whereNot('id', $this->id);
        }

        $prev_movement = $prev_movement_query->first();
        if ($prev_movement) {
            $prev_account_row = $prev_movement->account_rows()->first();
            if ($prev_account_row) {
                $remaining_amount = $this->getAccountRowsAmountDiffError();
                $remaining_plus_fee = bcadd($remaining_amount, $prev_account_row->amount, 2);
                if ($remaining_plus_fee > 0) {
                    $ar = new AccountRow;
                    $ar->movement_id = $this->id;
                    $ar->account_id = $prev_account_row->account_id;
                    $ar->user_id = $prev_account_row->user_id;
                    $ar->section_id = $prev_account_row->section_id;
                    $ar->notes = $prev_account_row->notes;
                    $ar->amount = $prev_account_row->amount;
                }
                return $ar;
            }
        }

        return null;
    }

    /**
     * Try to give a meaning to this Movement, from its note.
     * You can setup some regular expressions in each Bank configuration,
     * to match your Movement and propose an AccountRow.
     *
     * This method MAY modify some already-existing AccountRow(s) but
     * WITHOUT PERSISTING ANYTHING. Or, this method will just return some new
     * proposed AccountRow.
     *
     * To know what AccountRow was created or expanded, just look at what
     * AccountRow is flagged as "edited".
     *

resources/views/movement/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">

    @if ($object)
    <div class="row">
        <div class="col-lg-10">
            @if ($object->id)
                <h2>Modifica Movimento {{$object->id}}</h2>
            @else
                <h2>Crea Movimento</h2>
            @endif
        </div>
        <div class="col-lg-2">
            @include('movement.reviewcounter')
        </div>
    </div>
    @endif

    <div class="row">
        <div class="col-md-12">
            <form method="POST" action="{{ route('movement.update', ($object && $object->id) ? $object->id : 0) }}">
                @method('PUT')
                @csrf

                @include('movement.editblock', ['movement' => $object])

                <div class="form-group row">
                    <div class="col-sm-10">
                        <button type="submit" class="btn btn-primary">Salva</button>
                    </div>
                </div>
            </form>

            @if ($object && $object->id)
            <div class="card mt-3">
                <div class="card-header">Allegati</div>

                <div class="card-body">
                    <ul>
                        @foreach($object->attachments as $attach)
                            <li><a href="{{ route('movement.download', [ 'id' => $object->id, 'file' => $attach ]) }}">{{ basename($attach) }}</a></li>
                        @endforeach
                    </ul>

                    <form method="POST" action="{{ route('movement.attach', $object->id) }}" enctype="multipart/form-data">
                        @csrf

                        <div class="form-group row">
                            <div class="col-sm-4">
                                <input type="file" class="form-control" name="file">
                            </div>
                            <div class="col-sm-2">
                                <button type="submit" class="btn btn-primary">Allega File</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            @endif

            @if ($object && $object->amount > 0)
                <div class="card mt-3">
                    <div class="card-header">Ricevuta</div>

                    <div class="card-body">
                        @if($object->receipt)
                            <a class="btn btn-default" href="{{ $object->receipt->link }}">Scarica Ricevuta {{ $object->receipt->full_number }}</a>
                        @else
                            <form method="POST" action="{{ route('receipt.store') }}">
                                @csrf

                                <input type="hidden" name="movement_id" value="{{ $object->id }}">

                                <div class="form-group row">
                                    <label for="date" class="col-sm-4 col-form-label">Data</label>
                                    <div class="col-sm-8">
                                        <input type="text" class="form-control" name="date" value="{{ date('Y-m-d') }}">
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label for="header" class="col-sm-4 col-form-label">Intestazione</label>
                                    <div class="col-sm-8">
                                        <textarea class="form-control" name="header"></textarea>
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label for="causal" class="col-sm-4 col-form-label">Causale</label>
                                    <div class="col-sm-8">
                                        <textarea class="form-control" name="causal"></textarea>
                                    </div>
                                </div>

                                @if($object->amount >= 77.47)
                                    <div class="form-group row">
                                        <label for="stamp" class="col-sm-4 col-form-label">Marca da Bollo</label>
                                        <div class="col-sm-8">
                                            <input type="text" class="form-control" name="stamp">
                                        </div>
                                    </div>
                                @endif

                                <hr>
                                <div class="form-group row">
                                    <div class="col-sm-10">
                                        <button type="submit" class="btn btn-primary">Genera Ricevuta</button>
                                    </div>
                                </div>
                            </form>
                        @endif
                    </div>
                </div>
            @elseif ($object)
                <div class="card mt-3">
                    <div class="card-header">Rimborsi Spese</div>

                    <div class="card-body">
                        @if($object->refund->isEmpty() == false)
                            <ul>
                                @foreach($object->refund as $r)
                                    <li><a href="{{ route('refund.edit', $r->id) }}">{{ $r->printable_description }}</a></li>
                                @endforeach
                            </ul>
                        @else
                            <?php $pendings = App\Refund::where('refunded', false)->whereDoesntHave('movement')->get() ?>

                            @if($pendings->isEmpty())
                                <div class="alert alert-info">
                                    Non ci sono rimborsi spese in attesa.
                                </div>
                            @else
                                <form method="POST" action="{{ route('movement.refund', $object->id) }}">
                                    @csrf

                                    <fieldset class="form-group">
                                        <div class="row">
                                            <legend class="col-form-label col-sm-4 pt-0">Rimborsi in Attesa</legend>
                                            <div class="col-sm-8">
                                                @foreach($pendings as $p)
                                                    <div class="form-check">
                                                        <input class="form-check-input" type="checkbox" name="refund_id[]" value="{{ $p->id }}">
                                                        <label class="form-check-label">
                                                            {{ $p->printable_description }}
                                                        </label>
                                                    </div>
                                                @endforeach
                                            </div>
                                        </div>
                                    </fieldset>

                                    <div class="form-group row">
                                        <div class="col-sm-10">
                                            <button type="submit" class="btn btn-primary">Rimborsa</button>
                                        </div>
                                    </div>
                                </form>
                            @endif
                        @endif
                    </div>
                </div>
            @endif


            @if ($object->supportsRefresh())
            <div class="card mt-3">
                <div class="card-header">Strumenti</div>
                    <div class="card-body">
                        <form method="post" action="{{ route('movement.refresh', $object->id ) }}">
                            @csrf
                            <button type="submit" class="btn btn-primary">Ricarica da PayPal</button>
                       </form>
                   </div>
                </div>
           </div>
           @endif

        </div>
    </div>
</div>
@endsection

resources/views/movement/editblock.blade.php
@php
$start_of_year = $movement
  ? $movement->start_of_year
  : (int)request()->input('start_of_year', 0);

$bank_id = ($movement && $movement->bank)
  ? $movement->bank->id
  : (int)request()->input('bank_id', null);

$bank = $movement->bank ?? null;
if (!$bank && $bank_id) {
    $bank = App\Bank::where('id', $bank_id)->firstOrFail();
}

$date = $movement
  ? $movement->date
  : (string)request()->input('date', null);

// Allow to put an edit link for each Movement.
// Maybe undesired in single view. Maybe desired in review.
$readonly = $readonly ?? false;
$editlink = $editlink ?? false;
@endphp

<ul class="list-group">
    <li class="list-group-item">
        <div class="row">

            @if ($movement->id && $editlink)
            <div class="col-md-12">
                <h3><a href="{{ route('movement.edit', $movement->id) }}" title="Modifica Movimento {{$movement->id}}"><span class="oi oi-pencil"></span> Movimento {{$movement->id}}</a></h3>
                <hr />
            </div>
            @endif

            @if (!$movement->id && $start_of_year)
                <input type="hidden" name="start_of_year" value="{{ $start_of_year }}" />
            @endif

            @if (!$movement->id && $bank_id)
                <input type="hidden" name="bank_id" value="{{ $bank_id }}" />
            @endif

            @if ($start_of_year)
            <div class="col-md-12">
                <div class="alert alert-info" role="alert">
                  <h3>Saldo iniziale al 1° gennaio {{ $start_of_year }} per cassa {{ $bank->name }}</h3>
                  <p>Questo è un movimento speciale da poter compilare manualmente e che rappresenta il saldo della cassa <b>{{ $bank->name }}</b> al 1° gennaio {{ $start_of_year}} ore 00:00:00.
                     Nei dettagli vanno indicate le relative voci di entrata e uscita del {{ $start_of_year - 1 }}, fra cui il totale quote associative {{ $start_of_year -1 }}, totale spese di spedizione {{ $start_of_year -1 }}, ecc. esattamente come dovrai presentarlo all'assemblea per fare approvare il trascorso bilancio {{ $start_of_year - 1 }}.
                  </p>
                </div>
            </div>
            @endif

            <div class="col-md-3">
                @if ($movement->id)
                    {{ $movement->date }}<br />
                    <small>{{ $movement->bank ? $movement->bank->name : '' }} · <code>{{$movement->identifier ?? ''}}</code></small>
                @else
                    <input type="text" name="date" placeholder="YYYY-MM-DD" value="{{ $date }}" />
                @endif
            </div>

            <div class="col-md-3">
                @if ($movement->id)
                    @if ($movement->amount_original !== null)
                        <s title="Importo presente nella transazione originaria">{{ $movement->amount_original_formatted }}</s>
                        ·
                    @endif

                    <span title="Importo effettivamente presente sul nostro conto corrente - dopo aver applicato commissioni bancarie, ecc.">{{ $movement->amount_formatted }}</span>
                @else
                    <!-- Movement Amount. Pay attention to do not collide the name with the AccountRow's amount. -->
                    <input type="number" step="0.01" name="amount" placeholder="0.0" />
                @endif
            </div>
            <div class="col-md-6">
                @if ($movement->id)
                    <input type="text" readonly disabled value="{{ $movement->notes }}" placeholder="Causale" class="form-control" title="Causale originale" />
                @else
                <!-- Movement Notes. Pay attention to do not collide the name with the AccountRow's Notes. -->
                    <input type="text" name="notes" value="{{ $movement->notes }}" placeholder="Causale" />
                @endif

                <!-- Remove Movement: start -->
                @if( $movement->id && empty($movement->identifier) && !$readonly )
                <div class="form-check float-right text-right">
                    <p>
                    <input class="form-check-input" type="checkbox" name="remove[]" value="{{ $movement->id }}" id="remove{{ $movement->id }}">
                    <label class="form-check-label" for="remove{{ $movement->id }}">
                        Elimina
                    </label>
                    </p>
                </div>
                @endif
                <!-- Remove Movement: stop -->
            </div>
        </div>
    </li>

    <!-- Account Rows Sum warning: start -->
    @if( $movement && !$movement->findStubAccountRow() && !$movement->isAmountMatchingAccountRows() )
    <li class="list-group-item">
        <div class="alert alert-danger account-rows-sum-danger" role="alert">
          <p><b>Errore Sommatoria</b></p>
          <p>Correggere gli importi delle sottostanti righe contabili, affinché il loro totale corrisponda a quello del movimento bancario.<br />
             Scarto rilevato:
             <b class="account-rows-amount-diff-error">{{ sprintf('%.02f', $movement->getAccountRowsAmountDiffError() ) }}</b> EUR
          </p>
        </div>
    </li>
    @endif
    <!-- Account Rows Sum warning: end -->

    @if ($movement)
        <!-- Always show all AccountRow(s). Some of them are just proposed and unsaved. -->
        @foreach($movement->account_rows as $ar)
            @include('accountrow.editblock', [
                'ar' => $ar,
                'readonly' => $readonly,
            ])
        @endforeach
    @else
        @include('accountrow.editblock', ['ar' => null])
    @endif

    @if(!$readonly)
    <li class="list-group-item">
        <button class="btn btn-default btn-sm add-row"><span class="oi oi-plus"></span></button>
        <ul class="hidden">
            @include('accountrow.editblock', ['ar' => null])
        </ul>
    </li>
    @endif
</ul>

resources/views/movement/reviewcounter.blade.php
@php
$un_reviewed_movements = App\Movement::where('reviewed', 0)->count();
@endphp
@if($un_reviewed_movements)
    <a href="{{ route('movement.review') }}" class="btn btn-primary float-right">{{ $un_reviewed_movements }} Movimenti da Revisionare</a>
@endif