routes/web.php
<?php

use App\User;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// ERROR: Cannot use Illuminate\Support\Facades\Route as Route because the name is already in use
//use Illuminate\Support\Facades\Route;
//use Illuminate\Support\Facades\Auth;

Route::get('/', function () {
    if (Auth::check())
        return redirect()->route('home');
    else
        return redirect()->route('login');
});

// Register login, register, password-reset, and other lovely core stuff.
Auth::routes();

Route::get('register/thanks', 'Auth\RegisterController@thanks')->name('register.thanks');
Route::get('register/to/{city_slug}/{section_id}', 'Auth\RegisterController@sectionPreload')->name('register.tosection');

// **** developer stuff ****************************

Route::prefix('dev')->group(function () {
    // We support useful but very-dangerous auto-login workflows,
    // but first, you MUST have:
    //  - environment: local
    //  - env UNSAFE_QUICK_LOGIN_BACKDOOR: 1
    if (!app()->environment('local') || !env('DEV_QUICK_LOGIN_BACKDOOR')) {
        return;
    }

    Route::prefix('login')->group(function () {

        Route::get('admin', function () {
            $user = User::active()->ofRole('admin')->first();
            auth()->login($user);

            return redirect()->route('home');
        })->name('dev.login.admin');

        Route::get('member', function () {
            $user = User::active()->ofRole('member')->first();
            auth()->login($user);

            return redirect()->route('home');
        })->name('dev.login.member');

        Route::get('referent', function () {
            $user = User::active()->ofRole('referent')->first();
            auth()->login($user);

            return redirect()->route('home');
        })->name('dev.login.referent');

        Route::get('pending', function () {
            $user = User::pendingWithPaidFee()->first();
            auth()->login($user);

            return redirect()->route('home');
        })->name('dev.login.pending');

        Route::get('suspended', function () {
            $user = User::ofStatus('suspended')->first();
            auth()->login($user);

            return redirect()->route('home');
        })->name('dev.login.suspended');

        Route::get('expelled', function () {
            $user = User::ofStatus('expelled')->first();
            auth()->login($user);

            return redirect()->route('home');
        })->name('dev.login.expelled');

        Route::get('dropped', function () {
            $user = User::ofStatus('dropped')->first();
            auth()->login($user);

            return redirect()->route('home');
        })->name('dev.login.dropped');

        Route::get('association', function () {
            $user = User::actLikeMember()
              ->ofType('association')->first();
            auth()->login(User::find($user->id));

            return redirect()->route('home');
        })->name('dev.login.association');

        Route::get('limited', function () {
            $user = User::ofType('limited')->first();
            auth()->login($user);
            return redirect()->route('home');
        })->name('dev.login.limited');
    });
});

Route::middleware(['auth'])->group(function () {
    Route::get('home', 'HomeController@index')->name('home');

    Route::post('user/approve', 'UserController@approve')->name('user.approve');
    Route::get('user/bypass/{id}', 'UserController@bypass')->name('user.bypass');

    Route::get('movement/review', 'MovementController@review')->name('movement.review');
    Route::post('movement/attach/{id}', 'MovementController@attach')->name('movement.attach');
    Route::post('movement/refresh/{id}', 'MovementController@refresh')->name('movement.refresh');
    Route::post('movement/refund/{id}', 'MovementController@refund')->name('movement.refund');
    Route::get('movement/{id}/download/{file}', 'MovementController@download')->name('movement.download');

    Route::get('movement-detailed/export/all/csv', 'MovementDetailedController@exportAllCsv')->name('movement-detailed.export.all.csv');

    Route::get('section/{id}/balance', 'SectionController@balance')->name('section.balance');
    Route::post('section/{id}/exportmembers', 'SectionController@exportmembers')->name('section.exportmembers');

    Route::get('refund/{id}/download/quote/{file}', 'RefundController@downloadQuote')->name('refund.quote.download');
    Route::get('refund/{id}/download/receipt/{file}', 'RefundController@downloadReceipt')->name('refund.receipt.download');

    Route::get('sponsor/logo/{id}', 'SponsorController@logo')->name('sponsor.logo');

    Route::get('doc/download', 'DocumentationController@download')->name('doc.download');
    Route::get('doc/link', 'DocumentationController@link')->name('doc.link');
    Route::get('doc/preview', 'DocumentationController@preview')->name('doc.preview');

    Route::post('assembly/partecipate/{assembly_id}/{do}', 'AssemblyController@partecipate')->name('assembly.partecipate');
    Route::post('assembly/delegate/{assembly_id}/{delegate_id}', 'AssemblyController@delegate')->name('assembly.delegate');

   // Route::get('bank/list/', 'BankController@list')->name('bank.list_all');
   // Route::get('bank/list/{id}', 'BankController@list')->name('bank.list');

    Route::resource('user', 'UserController');
    Route::resource('volunteer', 'VolunteerController');
    Route::resource('doc', 'DocumentationController');
    Route::resource('config', 'ConfigController');
    Route::resource('bank', 'BankController');
    Route::resource('movement', 'MovementController');
    Route::resource('movement-detailed', 'MovementDetailedController');
    Route::resource('rule', 'RuleController');
    Route::resource('section', 'SectionController');
    Route::resource('receipt', 'ReceiptController');
    Route::resource('refund', 'RefundController');
    Route::resource('assembly', 'AssemblyController');
    Route::resource('votation', 'VotationController');
    Route::resource('vote', 'VoteController');
    Route::resource('sponsor', 'SponsorController');
    Route::resource('gadget-request', 'GadgetRequestController');
});

// Rotte per gli utenti ospiti
Route::get('gadget-request-track/{token}', 'GadgetRequestController@showByToken')->name('gadget-request.show-by-token');
Route::get('gadget-request-thank-you', 'GadgetRequestController@thankYou')->name('gadget-request.thank-you');
Route::get('gadget-request/create', 'GadgetRequestController@create')->name('gadget-request.create');
Route::post('gadget-request/store', 'GadgetRequestController@store')->name('gadget-request.store');

app/Refund.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Collection;

class Refund extends Model
{

    use ILSModel;

    /**
     * Get the generic name of this entity, singular.
     * This may be shown in a breadcrumb.
     * @return string
     */
    public function getEntityNameSingular()
    {
        return "Rimborso Spese";
    }

    /**
     * Get the object short name.
     * This may be shown in a breadcrumb.
     * @return string
     */
    public function getObjectShortName()
    {
        // TODO: have a title
        return $this->id;
    }

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function section()
    {
        return $this->belongsTo('App\Section');
    }

    public function movement()
    {
        return $this->belongsTo('App\Movement');
    }

    public function getPrintableDescriptionAttribute()
    {
        return sprintf('%s € - %s - %s', $this->amount, $this->user ? $this->user->printable_name : '?', $this->section ? 'Sezione Locale di ' . $this->section->city : 'Nessuna Sezione Locale');
    }

    public function getAttachmentsReceiptsPathAttribute()
    {
        return storage_path('refunds/' . $this->id);
    }

    public function getAttachmentsQuotesPathAttribute()
    {
        return storage_path('refunds/' . $this->id. '/quotes');
    }

    public function getAttachmentsReceiptsAttribute()
    {
        $ret = new Collection();
        $path = $this->attachments_receipts_path;
        if (file_exists($path)) {
            $files = scandir($path);
            foreach ($files as $f) {
                if (is_file($path . '/' . $f)) {
                    $ret->push($f);
                }
            }
        }

        return $ret;
    }

    /**
     * Get the RefundStatus object from this Refund, if any.
     * @return RefundStatus
     */
    public function getRefundStatusAttribute()
    {
        return RefundStatus::findByID($this->refunded);
    }

    public function getAttachmentsQuotesAttribute()
    {
        $ret = new Collection();

        $path = $this->attachments_quotes_path;
        if (file_exists($path)) {
            $files = scandir($path);
            foreach ($files as $f) {
                if (is_file($path . '/' . $f)) {
                    $ret->push($f);
                }
            }
        }

        return $ret;
    }

    public function attachReceipt($file)
    {
        $file->move($this->attachments_receipts_path, $file->getClientOriginalName());
    }

    public function attachQuote($file)
    {
        $file->move($this->attachments_quotes_path, $file->getClientOriginalName());
    }

}

resources/views/refund/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <form method="POST" action="{{ route('refund.update', $object->id) }}" enctype="multipart/form-data">
                @method('PUT')
                @csrf

                @include('refund.form', ['object' => $object])

                @if($object)
                <div class="form-group row">
                    <label for="section_id" class="col-sm-4 col-form-label">Stato</label>
                    <div class="col-sm-8">
                        @if($currentuser->hasRole('admin'))
                        <select class="form-control" id="refunded" name="refunded">
                            @foreach(\App\RefundStatus::all() as $status)
                                <option value="{{ $status->id }}" @selected($status->id == $object->refunded)>{{ $status->label }}</option>
                            @endforeach
                        </select>
                        @else
                            <!-- TODO: improve this graphically :) -->
                            <input type="text" value="{{ $object->refundStatus->label}}" readonly disabled>
                        @endif
                    </div>
                </div>
                @endif

                <hr>

                <div class="form-group row">
                    <div class="col-sm-10">
                        <button type="submit" class="btn btn-primary">Salva</button>
                    </div>
                </div>
            </form>

            <br>

            @can('delete', $object)
                <form method="POST" action="{{ route('refund.destroy', $object->id) }}">
                    @method('DELETE')
                    @csrf

                    <div class="form-group row">
                        <div class="col-sm-10">
                            <button type="submit" class="btn btn-danger">Elimina Richiesta di Rimborso Spese</button>
                        </div>
                    </div>
                </form>
            @endcan
        </div>
    </div>
</div>
@endsection

resources/views/refund/form.blade.php
<h2>Dati del rimborso</h2>

<div class="form-group row">
    <label for="amount" class="col-sm-4 col-form-label">Titolo</label>
    <div class="col-sm-8">
        <input type="text" class="form-control" name="title" value="{{ $object ? $object->title : '' }}" placeholder="Rimborso per ...">
        <p>
            Inserisci un breve <b>titolo</b> che riassuma a tutti la tua necessità o il tuo scopo.<br />
            <small class="form-text text-muted">Chi può leggere questo campo: tutti.</small>
        </p>
    </div>
</div>
<div class="form-group row">
    <label for="date" class="col-sm-4 col-form-label">Data</label>
    <div class="col-sm-8">
        <input type="text" class="form-control" name="date" value="{{ $object ? $object->date : date('Y-m-d') }}" required>
        <p>
            Inserisci una <b>data</b> indicativa di quando avrai bisogno di fare questa spesa.<br />
            Se non sai cosa inserire, chiarisci pure in descrizione.<br />
            Ti ringraziamo se stai pianificando la cosa con un certo anticipo!<br />
            <small class="form-text text-muted">Chi può leggere questo titolo: tutti.</small>
        </p>
    </div>
</div>
<div class="form-group row">
    <label for="amount" class="col-sm-4 col-form-label">Ammontare</label>
    <div class="col-sm-8">
        <input type="number" class="form-control" step="0.01" name="amount" value="{{ $object ? $object->amount : '' }}" required @readonly( $object && !$object->refundStatus->isEditableByUser($currentuser) )>
        <p>
            Inserisci il <b>totale</b> della tua stima di spesa massima rimborsabile prevista, IVA inclusa.
            Se la tua spesa prevede più articoli o più preventivi, qui
            puoi inserire semplicemente il totale previsto. Potrai allegare
            le singole ricevute o i singoli scontrini nell'apposito campo.<br />
            <small class="form-text text-muted">Chi può leggere questo ammontare: tutti.</small>
        </p>
    </div>
</div>
@if ($currentuser->hasRole('admin'))
    <div class="form-group row">
        <label for="user_id" class="col-sm-4 col-form-label">Utente</label>
        <div class="col-sm-8">
            @include('user.select', ['name' => 'user_id', 'select' => ($object ? $object->user_id : $currentuser->id)])
            <p>
                <small class="form-text text-muted">Chi può leggere questo campo: tutti.</small>
            </p>
        </div>
    </div>
@endif
<div class="form-group row">
    <label for="section_id" class="col-sm-4 col-form-label">Sezione Locale</label>
    <div class="col-sm-8">
        @include('section.select', ['name' => 'section_id', 'select' => ($object ? $object->section_id : 0)])
        <p>
            Se il tuo progetto coinvolge una <b>sezione locale</b> già esistente,
            selezionala, così potrai ricevere ulteriore revisione da loro, e accedere
            al loro fondo cassa. Tutto questo, solitamente, velocizza la tua richiesta.<br />
            <small class="form-text text-muted">Chi può leggere questo campo: tutti.</small>
        </p>
    </div>
</div>
<div class="form-group row multiple-files">
    <label for="file_quote" class="col-sm-4 col-form-label">Preventivi / Documentazione</label>
    <div class="col-sm-8">
        @if ($object)
            <ul>
                @foreach ($object->attachments_quotes as $attach)
                    <li><a href="{{ route('refund.quote.download', [ 'id' => $object->id, 'file' => $attach ] ) }}">{{ basename($attach) }}</a></li>
                @endforeach
            </ul>
        @endif

        <input type="file" name="file_quote[]" autocomplete="off" />
        <p>
        <small class="form-text text-muted">Si prega di allegare tutta la documentazione correlata: preventivi, stime, offerte...</small>
        <small class="form-text text-muted">Chi può accedere a questi preventivi: segreteria, referenti sezione locale.</small>
        </p>
    </div>
</div>
<!-- During creation, do not ask about receipts.
     First reason: to do not clogger the UX.
     Second reason: we encourage users in waiting for approvals first :D
       instead of pay-then-ask.
 -->
@if ($object)
<div class="form-group row multiple-files">
    <label for="file" class="col-sm-4 col-form-label">Ricevute / Fatture</label>
    <div class="col-sm-8">
        @if ($object)
            <ul>
                @foreach ($object->attachments_receipts as $attach)
                    <li><a href="{{ route('refund.receipt.download', [ 'id' => $object->id, 'file' => $attach ] ) }}">{{ basename($attach) }}</a></li>
                @endforeach
            </ul>
        @endif

        <input type="file" name="file_receipt[]" autocomplete="off" />
        <small class="form-text text-muted">Si prega di allegare tutta la documentazione correlata: fatture, scontrini, biglietti, ecc.</small>
        <small class="form-text text-muted">Chi può accedere a queste ricevute: segreteria, referenti sezione locale.</small>
    </div>
</div>
@endif
<div class="form-group row">
    <label for="notes" class="col-sm-4 col-form-label">Note richiedente</label>
    <div class="col-sm-8">
        <textarea class="form-control" name="notes" placeholder="Scrivere qui una breve descrizione delle spese affrontate e di come desideri ricevere il rimborso (fornisci un IBAN, ecc.)" required>{{ $object ? $object->notes : '' }}</textarea>
        <p>
            <small class="form-text text-muted">Chi può leggere le tue note: segreteria, referenti sezione locale.</small>
        </p>
    </div>
</div>

@if ($object)
<hr />

<div class="form-group row">
    <label for="report_url" class="col-sm-4 col-form-label">Relazione Finale (URL)</label>
    <div class="col-sm-8">
        <input type="text" class="form-control" name="report_url" placeholder="https://" value="{{ $object ? $object->report_url : '' }}" />
        <p>La relazione finale è una breve e graziosa pagina web che descriva a tutti come si è svolta la vostra attività. La puoi pubblicare su un qualsiasi sito (o forum ecc.) per descrivere cosa è andato bene, cosa sarebbe potuto andare meglio, come sono stati effettivamente utilizzati i fondi e descrivendo i risultati attesi e i risultati ottenuti. Non dimenticare qualche bella foto (fai punti bonus se sono in licenza libera!) e non dimenticarti di dare i giusti crediti e ringraziamenti alle persone e organizzazioni che hanno partecipato e vi hanno sostenuto moralmente o economicamente.</p>
        <p>
            <small class="form-text text-muted">Chi può leggere la relazione finale: tutti.</small>
        </p>
    </div>
</div>

<h2>Dati dalla Segreteria</h2>

<div class="form-group row">
    <label for="admin_notes" class="col-sm-4 col-form-label">Note Segreteria</label>
    <div class="col-sm-8">
        <textarea class="form-control" name="admin_notes" placeholder="Informazioni dell'amministratore riguardo lo stato di avanzamento del rimborso" {{ $currentuser->hasRole('admin') ? '' : 'readonly' }}>{{ $object ? $object->admin_notes : '' }}</textarea>
    </div>
</div>
@endif

resources/views/refund/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="jumbotron">
                <h2 class="display-4">Richieste di sostegno economico</h2>
                <p class="lead">In questa pagina chiunque può vedere <b>tutte</b> le richieste di sostegno economico o rimborsi spese ed è possibile inoltrare una nuova richiesta, seguendo il regolamento, con massima trasparenza.</p>
                <p>Alcune informazioni sono visibili solo alla segreteria e a chi è referente delle sezioni locali di riferimento.
                   Quindi, se queste informazioni non ti sono sufficienti e vuoi ulteriore trasparenza, contatta in quest'ordine: chi è richiedente, la sezione locale, o la segreteria,
                   per accedere (per esempio) ai preventivi o alle fatture che ti forniremo volentieri ma ovviamente in formato il più possibile anonimizzato, senza quindi condividere informazioni di fatturazione dei beneficiari, ecc.
                </p>
                <p>Siamo tutti invitati nel dare una mano, facendo una revisione, condividendo critiche costruttive, dando un parere nei vari canali (chat, ...) e dando soprattutto sostegno morale a questi progetti.
                   Grazie ai richiedenti che curano i loro report, grazie a chi fra voi aiuterà i richiedenti nel scriverli nei tempi previsti e grazie a chi li condivide o li commenta sui social.</p>
                <p><b>Attenzione</b>: i report sono potenzialmente <u>link esterni</u> curati dal richiedente, con politiche sulla privacy potenzialmente diverse dalla nostra.</p>
                <hr class="my-4">
                <p class="lead">
                    <a class="btn btn-primary btn-lg" href="{{ \App\Config::getConfig('refund_info_url') }}" role="button">Come funzionano i rimborsi</a>
                </p>
            </div>
        </div>
        <div class="col-md-12">
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#createUser">Nuovo Rimborso Spese</button>
            <div class="modal fade" id="createUser" tabindex="-1" role="dialog">
                <div class="modal-dialog modal-lg" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title">Nuovo Rimborso Spese</h5>
                            <button type="button" class="close" data-dismiss="modal">
                                <span>&times;</span>
                            </button>
                        </div>
                        <form method="POST" action="{{ route('refund.store') }}" enctype="multipart/form-data">
                            @csrf
                            <div class="modal-body">
                                @include('refund.form', ['object' => null])
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Annulla</button>
                                <button type="submit" class="btn btn-primary">Salva</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <form method="GET" action="" class="auto-filter-form">
        <div class="row mt-3">
            <div class="col-md-3">
                <div class="form-group">
                    <label for="refunded">Stato:</label>

                    @foreach($all_statuses as $status)
                        <div>
                            <input id="refund-uid-{{ $status->uid }}" type="checkbox" name="status[]" value="{{ $status->uid }}" @checked(in_array($status->uid, $selected_refund_status_uids))>
                            <label for="refund-uid-{{ $status->uid }}" class="tip" title="{{ $status->description }}">{{ $status->label }} </label>
                        </div>
                    @endforeach
                </div>
            </div>

            @if($currentuser->hasRole('admin'))
            <div class="col-md-3">
                <div class="form-group">
                    <label for="user_id">Richiedente:</label>
                    <select id="user_id" name="user_id" class="form-control">
                        <option value="">Tutti</option>

                        @foreach($users as $user)
                            <option value="{{ $user->id }}" @selected(app('request')->input('user_id') == $user->id)>{{ $user->printable_name }}</option>
                        @endforeach
                    </select>
                </div>
            </div>
            @endif

            <div class="col-md-3">
                <div class="form-group">
                    <label for="section_id">Sezione:</label>
                    <select id="section_id" name="section_id" class="form-control">
                        <option value="">Tutte</option>

                        @foreach($sections as $section)
                            <option value="{{ $section->id }}" @selected(app('request')->input('section_id') == $section->id)>{{ $section->city }}</option>
                        @endforeach
                    </select>
                </div>
            </div>

            <div class="col-md-3">
                <div class="form-group">
                    <label for="year">Anno:</label>
                    <select name="year" id="year" class="form-control">
                        <option value="">Tutti</option>
                        @for($y=$max_year; $y>=$min_year; $y--)
                            <option value="{{ $y }}" @selected($year == $y)>{{ $y }}</option>
                        @endfor
                    </select>
                </div>
            </div>

            <div class="col-md-3">
                <div class="form-group">
                    <label for="reporturl">Report:</label>
                    <select id="reporturl" name="report" class="form-control">
                        @foreach($report_options as $value => $label)
                            <option value="{{ $value }}" @selected($value === app('request')->input('report'))>{{ $label }}</option>
                        @endforeach
                    </select>
                </div>
            </div>
        </div>
    </form>

    <div class="row mt-3">
        <div class="col-md-12">
            <table class="table">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Data</th>
                        <th>Titolo</th>
                        <th>Richiedente</th>
                        <th>Sezione</th>
                        <th>Importo</th>
                        <th>Da rimborsare</th>
                        <th>Stato</th>
                        <th>Report</th>
                        <th>Dettagli</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($objects as $refund)
                        <tr>
                            <td>{{ $refund->id }}</td>
                            <td>{{ $refund->date }}</td>
                            <td>{{ $refund->title ?? '' }}</td>
                            <td>{{ $refund->user ? $refund->user->printable_name : '' }}</td>
                            <td>{{ $refund->section ? $refund->section->city : '' }}</td>
                            <td class="text-right">{{ $refund->amount }}</td>
                            <td class="text-right">{{ $refund->refundStatus->completed ? '0.00' : $refund->amount }}</td>
                            <td class="text-center">
                                {{ $refund->refundStatus->label }}
                                <br>
                                <div class="progress mini-progress-bar">
                                    <div class="progress-bar bg-{{ $refund->refundStatus->color }}" role="progressbar" style="width: {{ $refund->refundStatus->percent }}%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
                                </div>
                            </td>
                            <td>
                                @if ($refund->report_url)
                                <a class="btn" href="{{ $refund->report_url }}" target="_blank" title="Apri report del rimborso {{ $refund->id }}. {{ $refund->title }}"><span class="oi oi-globe"></span></a>
                                @else
                                <abbr title="Non disponibile. Se il/la richiedente è in ritardo con la consegna. Contatta la persona per dare una mano.">n.d.</abbr>
                                @endif
                            </td>
                            <td>
                                <!-- Always show the edit link, just disable to non-admins, so it's easier to test :)
                                     We don't do security by obscurity. -->
                                <a href="{{ route('refund.edit', $refund->id) }}" class="btn {{ \Auth::user()->can('update', $refund) ? '' : 'disabled' }}"><span class="oi oi-pencil"></span></a>
                            </td>
                        </tr>
                    @endforeach
                </tbody>

                <tfoot>
                    <tr>
                        <th colspan="4"></th>
                        <th>Totali:</th>
                        <td class="text-right">{{ format_amount($total) }}</td>
                        <td class="text-right">{{ format_amount($total_refunded) }}</td>
                        <td colspan="3"></td>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>
@endsection