routes/web.php
<?php

use App\User;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// ERROR: Cannot use Illuminate\Support\Facades\Route as Route because the name is already in use
//use Illuminate\Support\Facades\Route;
//use Illuminate\Support\Facades\Auth;

Route::get('/', function () {
    if (Auth::check())
        return redirect()->route('home');
    else
        return redirect()->route('login');
});

// Register login, register, password-reset, and other lovely core stuff.
Auth::routes();

Route::get('register/thanks', 'Auth\RegisterController@thanks')->name('register.thanks');
Route::get('register/to/{city_slug}/{section_id}', 'Auth\RegisterController@sectionPreload')->name('register.tosection');

// **** developer stuff ****************************

Route::prefix('dev')->group(function () {
    // We support useful but very-dangerous auto-login workflows,
    // but first, you MUST have:
    //  - environment: local
    //  - env UNSAFE_QUICK_LOGIN_BACKDOOR: 1
    if (!app()->environment('local') || !env('DEV_QUICK_LOGIN_BACKDOOR')) {
        return;
    }

    Route::prefix('login')->group(function () {

        Route::get('admin', function () {
            $user = User::active()->ofRole('admin')->first();
            auth()->login($user);

            return redirect()->route('home');
        })->name('dev.login.admin');

        Route::get('member', function () {
            $user = User::active()->ofRole('member')->first();
            auth()->login($user);

            return redirect()->route('home');
        })->name('dev.login.member');

        Route::get('referent', function () {
            $user = User::active()->ofRole('referent')->first();
            auth()->login($user);

            return redirect()->route('home');
        })->name('dev.login.referent');

        Route::get('pending', function () {
            $user = User::pendingWithPaidFee()->first();
            auth()->login($user);

            return redirect()->route('home');
        })->name('dev.login.pending');

        Route::get('suspended', function () {
            $user = User::ofStatus('suspended')->first();
            auth()->login($user);

            return redirect()->route('home');
        })->name('dev.login.suspended');

        Route::get('expelled', function () {
            $user = User::ofStatus('expelled')->first();
            auth()->login($user);

            return redirect()->route('home');
        })->name('dev.login.expelled');

        Route::get('dropped', function () {
            $user = User::ofStatus('dropped')->first();
            auth()->login($user);

            return redirect()->route('home');
        })->name('dev.login.dropped');

        Route::get('association', function () {
            $user = User::actLikeMember()
              ->ofType('association')->first();
            auth()->login(User::find($user->id));

            return redirect()->route('home');
        })->name('dev.login.association');

        Route::get('limited', function () {
            $user = User::ofType('limited')->first();
            auth()->login($user);
            return redirect()->route('home');
        })->name('dev.login.limited');
    });
});

Route::middleware(['auth'])->group(function () {
    Route::get('home', 'HomeController@index')->name('home');

    Route::post('user/approve', 'UserController@approve')->name('user.approve');
    Route::get('user/bypass/{id}', 'UserController@bypass')->name('user.bypass');

    Route::get('movement/review', 'MovementController@review')->name('movement.review');
    Route::post('movement/attach/{id}', 'MovementController@attach')->name('movement.attach');
    Route::post('movement/refresh/{id}', 'MovementController@refresh')->name('movement.refresh');
    Route::post('movement/refund/{id}', 'MovementController@refund')->name('movement.refund');
    Route::get('movement/{id}/download/{file}', 'MovementController@download')->name('movement.download');

    Route::get('movement-detailed/export/all/csv', 'MovementDetailedController@exportAllCsv')->name('movement-detailed.export.all.csv');

    Route::get('section/{id}/balance', 'SectionController@balance')->name('section.balance');
    Route::post('section/{id}/exportmembers', 'SectionController@exportmembers')->name('section.exportmembers');

    Route::get('refund/{id}/download/quote/{file}', 'RefundController@downloadQuote')->name('refund.quote.download');
    Route::get('refund/{id}/download/receipt/{file}', 'RefundController@downloadReceipt')->name('refund.receipt.download');

    Route::get('sponsor/logo/{id}', 'SponsorController@logo')->name('sponsor.logo');

    Route::get('doc/download', 'DocumentationController@download')->name('doc.download');
    Route::get('doc/link', 'DocumentationController@link')->name('doc.link');
    Route::get('doc/preview', 'DocumentationController@preview')->name('doc.preview');

    Route::post('assembly/partecipate/{assembly_id}/{do}', 'AssemblyController@partecipate')->name('assembly.partecipate');
    Route::post('assembly/delegate/{assembly_id}/{delegate_id}', 'AssemblyController@delegate')->name('assembly.delegate');

   // Route::get('bank/list/', 'BankController@list')->name('bank.list_all');
   // Route::get('bank/list/{id}', 'BankController@list')->name('bank.list');

    Route::resource('user', 'UserController');
    Route::resource('volunteer', 'VolunteerController');
    Route::resource('doc', 'DocumentationController');
    Route::resource('config', 'ConfigController');
    Route::resource('bank', 'BankController');
    Route::resource('movement', 'MovementController');
    Route::resource('movement-detailed', 'MovementDetailedController');
    Route::resource('rule', 'RuleController');
    Route::resource('section', 'SectionController');
    Route::resource('receipt', 'ReceiptController');
    Route::resource('refund', 'RefundController');
    Route::resource('assembly', 'AssemblyController');
    Route::resource('votation', 'VotationController');
    Route::resource('vote', 'VoteController');
    Route::resource('sponsor', 'SponsorController');
    Route::resource('gadget-request', 'GadgetRequestController');
});

// Rotte per gli utenti ospiti
Route::get('gadget-request-track/{token}', 'GadgetRequestController@showByToken')->name('gadget-request.show-by-token');
Route::get('gadget-request-thank-you', 'GadgetRequestController@thankYou')->name('gadget-request.thank-you');
Route::get('gadget-request/create', 'GadgetRequestController@create')->name('gadget-request.create');
Route::post('gadget-request/store', 'GadgetRequestController@store')->name('gadget-request.store');

app/User.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Auth\Notifications\ResetPassword as ResetPasswordNotification;
use Illuminate\Http\Request;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Mail;
use Laravel\Passport\HasApiTokens;

use App\Config;
use App\UserType;

class User extends Authenticatable
{
    use HasApiTokens;
    use ILSModel;
    use Notifiable;

    const STATUS_ACTIVE = 'active';

    /**
     * Get the generic name of this entity, singular.
     * This may be shown in a breadcrumb.
     * @return string
     */
    public function getEntityNameSingular()
    {
        return "Utenza";
    }

    /**
     * Get the object short name.
     * This may be shown in a breadcrumb.
     * @return string
     */
    public function getObjectShortName()
    {
        return $this->username;
    }

    protected $hidden = [
        'password', 'remember_token',
    ];

    public function configs()
    {
        return $this->morphMany('App\Config', 'subject');
    }

    public function roles()
    {
        return $this->belongsToMany('App\Role');
    }

    public function section()
    {
        return $this->belongsTo('App\Section');
    }

    public function fees()
    {
        return $this->hasMany('App\Fee');
    }

    public function accountRows()
    {
        return $this->hasMany('App\AccountRow');
    }

    public function donations()
    {
        $account_donation = Account::where('donations', 1)->firstOrFail();

        return $this->accountRows()
            ->where('account_id', $account_donation->id)
            ->join('movements', 'account_rows.movement_id', '=', 'movements.id');
    }

    public function refunds()
    {
        return $this->hasMany('App\Refund');
    }

    public function notifications()
    {
        return $this->hasMany(Notification::class);
    }

    /**
     * Scope a query to only include users that acts like a member,
     * including active users (indeed) and pending users with
     * at least one fee.
     */
    public function scopeActLikeMember(Builder $query): void
    {
        $query->where(function($query_p) {
            // Active members always can login.
            $query_p->orWhere(function($query_1) {
                $query_1->active();
            });

            // Pending members can login only with a recent fee.
            $query_p->orWhere(function($query_2) {
                $query_2->pendingWithPaidFee();
            });
        });
    }

    /**
     * Scope a query to only include active users.
     */
    public function scopeActive(Builder $query): void
    {
        // This calls scopeOfStatus().
        $query->ofStatus('active');
    }

    /**
     * Scope a query to only include pending users.
     */
    public function scopePending(Builder $query): void
    {
        // This calls scopeOfStatus().
        $query->ofStatus('pending');
    }

    /**
     * Scope a query to only include pending users that can login,
     * or that can act like a member, since they paid their fee.
     */
    public function scopePendingWithPaidFee(Builder $query): void
    {
        $query->pending();
        $query->hasFeeAtYearOrFuture();
    }

    /**
     * Scope a query to only include pending users that cannot login,
     * since they have not paid their fee.
     */
    public function scopePendingWithoutPaidFee(Builder $query): void
    {
        $query->pending();
        $query->whereNot(function($sub_query) {
            $sub_query->hasFeeAtYearOrFuture();
        });
    }

    /**
     * Scope a query to only include users with a specific status.
     * https://laravel.com/docs/11.x/eloquent#dynamic-scopes
     */
    public function scopeOfStatus(Builder $query, string $status): void
    {
        $query->where('status', $status);
    }
    
    /**
     * Scope a query to only include users with a specific type.
     * https://laravel.com/docs/11.x/eloquent#dynamic-scopes
     */
    public function scopeOfType(Builder $query, string $type): void
    {
        $query->where('type', $type);
    }

    /**
     * Scope a query to only include users with a specific role.
     * https://laravel.com/docs/11.x/eloquent#dynamic-scopes
     */
    public function scopeOfRole(Builder $query, string $role_name): void
    {
        $query->whereHas('roles', function ($sub_query) use ($role_name) {
            $sub_query->where('name', $role_name);
        });
    }

    /**
     * Scope a query to only include users WITH a fee on a specific year
     * or in any future year.
     * As default it considers the current year.
     */
    public function scopeHasFeeAtYearOrFuture(Builder $query, ?int $year = null): void
    {
        if (!$year) {
            $year = date('Y');
        }
        $query->whereHas('fees', function ($sub_query) use ($year) {
            $sub_query->where('year', '>=', $year);
        });
    }

    /**
     * Scope a query to only include users WITH a fee on a specific year.
     */
    public function scopeHasFee(Builder $query, int $year): void
    {
        $query->whereHas('fees', function ($sub_query) use ($year) {
            $sub_query->where('year', $year);
        });
    }

    /**
     * Scope a query to only include users WITHOUT a fee on a specific year.
     */
    public function scopeHasNotFee(Builder $query, int $year): void
    {
        $query->whereDoesntHave('fees', function ($sub_query) use ($year) {
            $sub_query->where('year', $year);
        });
    }

    /**
     * Scope a query to only include users that do not have a notification name.
     */
    public function scopeDoesntHaveNotification(Builder $query, string $command_name): void
    {
        $query->whereDoesntHave('notifications', function($sub_query) use ($command_name) {
            $sub_query->commandName($command_name);
        });
    }

    public function getPrintableNameAttribute()
    {
        return sprintf('%s %s', $this->surname, $this->name);
    }

    public function getFullAddressAttribute()
    {
        return sprintf("%s\n%s (%s)", $this->address_street, $this->address_place, $this->address_prov);
    }

    public function getCustomEmailAttribute()
    {
        if (Config::getConfig('custom_email_aliases') == '1') {
            return sprintf('%s@%s', $this->username, Config::getConfig('custom_email_domain'));
        }
        else {
            return null;
        }
    }

    /**
     * Get the UserType object of this user.
     * @return UserType
     */
    public function getUserTypeAttribute()
    {
        return UserType::find_by_identifier_or_fail($this->type);
    }

    public function getHumanStatusAttribute()
    {
        $statuses = self::statuses();

        foreach($statuses as $s) {
            if ($s->identifier == $this->status)
                return $s->label;
        }

        Log::error('Stato utente non riconosciuto: ' . $this->status);
        return '';
    }

    /**
     * Check whenever this user generally should pay a Fee.
     *
     * @return bool
     */
    public function getActsLikeMemberAttribute()
    {
        // This is generally false for 'guest'.
        return $this->userType->member;
    }

    /**
     * Get the fee that this user is expected to pay, yearly.
     * Note that this may have no sense for guests.
     * Before reading this, you may want to call the attribute "actsLikeMember"
     * first.
     * @return string
     */
    public function getFeeAmountAttribute()
    {
        static $cache = 0;
        if ($cache === 0) {
            // This is 'regular' or 'association' or 'guest' in most cases.
            $type_identifier = $this->userType->identifier;

            // It does not exist an option for "guests" fee.
            // So, just fallback to the default one.
            if (!$this->userType->member) {
                $type_identifier = UserType::DEFAULT_MEMBER_IDENTIFIER;
            }

            $cache = Config::getConfig($type_identifier . '_annual_fee');
        }
        return $cache;
    }

    public function firstMissingFeeYear()
    {
        $this_year = date('Y');

        $last_fee_year = null;
        $last_fee = $this->fees()->orderBy('year', 'desc')->first();
        if (!is_null($last_fee)) {
            $last_fee_year = $last_fee->year;
        }

        // If the account has been suspended, do not start from the last Fee, that may be 10 years in the past.
        //
        // Practical Desired Examples (assuming year is 2024):
        //   ActiveUser with last fee 1999: +1 (NOTE: the user MAY want to be suspended in this case)
        //   ActiveUser with last fee 2023: +1
        //   ActiveUser with last fee 2024: +1
        //   ActiveUser with last fee 2099: +1
        //   Suspended  with last fee 1999: start from this year
        //   Suspended  with last fee 2023: start from this year
        //   Suspended  with last fee 2024: +1 (don't care corner case - usually users are not suspended with recent fees... but this makes sense)
        //   Suspended  with last fee 2099: +1 (don't care corner case - usually users are not suspended with recent fees... but keeping your good score makes sense)
        //   ActiveUser without fee:        start from this year
        //   Suspended  without fee:        start from this year
        if (!$this->isStatus(self::STATUS_ACTIVE) && $last_fee_year && $last_fee_year < $this_year) {
            $last_fee_year = null;
        }

        if ($last_fee_year) {
            /*
                Qui c'è un errore deliberato, dovrebbe essere
                if ($last_fee->year < $this_year)
                Viene temporaneamente mantenuto così fino al rinnovo dello
                Statuto, sarà da correggere nel prossimo futuro
            */
            if ($last_fee < $this_year)

resources/views/user/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <form method="POST" action="{{ route('user.update', $object->id) }}">
                @method('PUT')
                @csrf

                @include('user.form', ['object' => $object])

                <hr>

                <div class="form-group row">
                    <div class="col-sm-10">
                        <button type="submit" class="btn btn-primary">Salva</button>
                    </div>
                </div>
            </form>

            @if($currentuser->hasRole('admin') && $object->status == 'pending')
                <form method="POST" action="{{ route('user.destroy', $object->id) }}">
                    @method('DELETE')
                    @csrf

                    <div class="form-group row">
                        <div class="col-sm-10">
                            <button type="submit" class="btn btn-danger">Elimina</button>
                        </div>
                    </div>
                </form>
            @endif
        </div>
        <div class="col-md-3 offset-md-1">
            <h5>Quote Versate</h5>

            @if($object->fees()->count() == 0)
                @if($object->actsLikeMember)
                    <!-- Be scary with members without a Fee! lol -->
                    <div class="alert alert-danger">
                        <p>Nessuna quota versata sinora.</p>

                        @if ($paypal_fee_url)
                        <div><a class="btn btn-primary" href="{{ $paypal_fee_url }}" title="Versa quota associativa con PayPal" target="_blank">Versa quota con PayPal</a></div>
                        @endif
                    </div>
                @else
                    <!-- Be welcoming with people that are NOT supposed to be members. -->
                    <div class="alert alert-info">
                        <p>Non hai richiesto di associarti. In ogni caso, puoi farlo compilando i dati del tuo profilo e versando la quota associativa.</p>
                        @if ($paypal_fee_url)
                        <div><a class="btn btn-primary" href="{{ $paypal_fee_url }}" title="Versa quota associativa con PayPal" target="_blank">Versa quota con PayPal</a></div>
                        @endif
                    </div>
                @endif
            @else
                <ul class="list-group">
                    @foreach($object->fees()->orderBy('year', 'desc')->get() as $fee)
                        <li class="list-group-item">
                            {{ $fee->year }}

                            @if($currentuser->hasRole('admin') && isset($fee->account_row))
                                <a href="{{ route('movement.edit', $fee->account_row->movement_id) }}" title="Modifica Movimento {{ $fee->account_row->movement_id }}"><span class="oi oi-pencil"></span></a>
                            @endif

                            @if($fee->receipt())
                                <span class="float-right"><a href="{{ $fee->receipt()->link }}">Ricevuta {{ $fee->receipt()->number }}</a></span>
                            @endif
                        </li>
                    @endforeach
                </ul>
            @endif

            <h5 class="mt-4">Donazioni Effettuate</h5>
            @if($object->donations()->count() == 0)
                <div class="alert alert-secondary">
                    In questo spazio archivieremo con cura le ricevute delle tue ulteriori donazioni spontanee,
                    per esempio quando usi la funzione <a href="{{ $paypal_donate_url ?? '#' }}">dona con PayPal</a>.
                </div>
            @else
                <ul class="list-group">
                    <!-- TODO: order by movement.date -->
                    @foreach($object->donations()->orderBy('movements.date', 'desc')->get() as $donation)
                        <li class="list-group-item">
                            @if($donation->movement && $donation->movement->receipt)
                                <span class="float-right">
                                    <a href="{{ $donation->movement->receipt->link }}">Ricevuta {{ $donation->movement->receipt->number }}</a>
                                </span>
                                @endif
                            {{ $donation->movement->date->format('d-m-Y') }}

                            @if($currentuser->hasRole('admin'))
                                <a href="{{ route('movement.edit', $donation->movement->id) }}" title="Modifica Movimento {{ $donation->movement->id }}"><span class="oi oi-pencil"></span></a>
                            @endif
                            <br>

                            &euro; {{ $donation->movement->amountFormatted }}
                        </li>
                    @endforeach
                </ul>
            @endif
        </div>
    </div>
</div>
@endsection

resources/views/user/select.blade.php
<?php

if (!isset($name))
    $name = 'user[]';

if (!isset($select))
    $select = 0;

if (!isset($status)) {
    $status = array_map(function($n) {
        return $n->identifier;
    }, App\User::statuses());
}
else if (!is_array($status)) {
    $status = [$status];
}

$classes = 'form-control';
if(isset($extra_classes)) {
    $classes .= " $extra_classes";
}

$disabled = $disabled ?? false;
?>
<select class="{{ $classes }}" name="{{ $name }}" autocomplete="off" @disabled($disabled)>
    <option value="" {{ $select == 0 ? 'selected' : '0' }}>Nessuno</option>
    @foreach(App\User::whereIn('status', $status)->orderBy('surname', 'asc')->get() as $user)
        <option value="{{ $user->id }}" {{ $select == $user->id ? 'selected' : '' }}>{{ $user->printable_name }} ({{ $user->username }})</option>
    @endforeach
</select>